[build]
  command = "npm run build" # or your build command
  publish = "build"          # or your build directory
  functions = ".netlify/functions"


[functions]
  directory = ".netlify/functions"



[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
